
name: hadoop-spark 
services:
  hadoop-single-node:
    build: .
    ports:
      - 9870:9870       # HDFS NameNode UI
      - 8088:8088       # YARN ResourceManager UI
      - 8080:8080       # Spark Master UI
      - 7077:7077       # Spark Master Port
      - 8888:8888       # Jupyter Notebook  
    environment:
      - HADOOP_HOME=/usr/local/hadoop
      - SPARK_HOME=/usr/local/spark
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_CONF_DIR=/usr/local/hadoop/hadoop/etc/hadoop
      - PATH=/usr/local/hadoop/hadoop/bin:/usr/local/hadoop/hadoop/sbin:/usr/local/spark/bin:/usr/local/spark/sbin:$PATH
      - HADOOP_MAPRED_HOME=/usr/local/hadoop 
      - HADOOP_COMMON_HOME=/usr/local/hadoop
      - HADOOP_HDFS_HOME=/usr/local/hadoop
      - HADOOP_YARN_HOME=/usr/local/hadoop
      - HADOOP_TOOLS_HOME=/usr/local/hadoop
      - HADOOP_COMMON_LIB_NATIVE_DIR=/usr/local/hadoop/hadoop/lib/native
    container_name: single-node-hadoop-spark
    hostname: single-node-hadoop-spark
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    volumes:
      - notebooks:/root/notebooks
    command: >
      sh -c "service ssh start && bash"


volumes:
  # Define a volume for Jupyter notebooks
  notebooks:

